### ISSUE TITLE
Could you please add some usage examples?

### ISSUE THREAD

**Issue by ndbroadbent** [jjjacksn/JMJParametricAnimation#1]
Hi there, I had a hard time figuring out how to use your library. I was wondering if you could please add some quick examples?

**Comment by jjjacksn** [comment]
Sure thing. is there any specific example you'd like to see?

**Comment by ndbroadbent** [comment]
Awesome, thanks! Just basic usage would be helpful.

Actually, super bonus points if you are able to get it to work in a Swift project. I'm trying to call it from Swift, myself. But don't know how to use it from Objective C either.

**Comment by jjjacksn** [comment]
Sorry I've been super busy, but just chance to play around with Swift a bit. If you aren't familiar with how to use Objective-C code from Swift, check out Apple's [Mix and Match Guide](https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html)

First make sure to import the header in your Objective-C bridging header.

```
#import "JMJParametricAnimation.h"
```

Then in your swift file...

```
  var animatedView: UIView! // view to animate
  var startPoint: CGPoint! // starting position
  var endPoint: CGPoint! // ending position

// example moving view from start to end with slight overshot and correction (ease out back)
func animate() {
  UIView.animateKeyPath("center", object: self.animatedView, duration: 2.0, delay: 0, 
    completion: { (completed: Bool) -> Void in
      NSLog("finished animation")
    }, timeFxn: JMJParametricAnimationTimeBlockBackOut,
    fromPoint: startPoint, toPoint: endPoint);
}

```

In addition to methods for points, there are methods for doubles, colors, rects, sizes and arbitrary NSValues.

Let me know if you there are any more specific examples you'd like to see.
